import greenfoot.*;
import java.util.ArrayList;

/**
 * Fixed-position inventory display that appears on screen regardless of camera position.
 * Always stays in the same screen position while the world scrolls.
 * 
 * Images generated by Leonardo.ai
 * 
 * @author Robin, Paul & Claude
 */
public class IconDisplay extends ScrollingActor {
    // Image variables
    private GreenfootImage openInv = new GreenfootImage("openInv.png");
    private GreenfootImage closedInv = new GreenfootImage("closedInv.png");
    private int screenX, screenY;
    private boolean isOpen = false;
    private boolean tabWasDown = false;

    // Inventory utility
    private ArrayList<InventoryItem> items;
    private int[][] slotLocations; // set this
    private int maxSlots = 15;

    /**
     * Create inventory display at a fixed screen position
     * 
     * @param screenX X position on screen (not world position)
     * @param screenY Y position on screen (not world position)
     */
    public IconDisplay(int screenX, int screenY, Camera camera) {
        super(camera);
        this.screenX = screenX;
        this.screenY = screenY;
        this.items = new ArrayList<InventoryItem>();

        // scale images
        closedInv.scale(100, 100);
        closedInv.setTransparency(225);
        openInv.scale(600, 600);
        openInv.setTransparency(242);
        setImage(closedInv);
        setLocation(screenX - 60, screenY - 60);
    }

    /**
     * Keep inventory at fixed screen position
     */
    public void act() {
        checkTabPress();
        checkMouseClick();
        updateImage();
    }

    private void checkMouseClick(){
        boolean mouseClickedInv = Greenfoot.mousePressed(this);
        boolean mouseIsDown = Greenfoot.mousePressed(null);
        
        if(!isOpen){
            // Click the icon to switch 
            if(mouseClickedInv){
                isOpen = !isOpen; // Toggle on new key press
                updateImage();
            }
        }else {
            // Click outside of inventory to switch
            if(!mouseClickedInv && mouseIsDown){
                isOpen = !isOpen;
                updateImage();
            }
        }
    }

    private void checkTabPress(){
        boolean tabIsDown = Greenfoot.isKeyDown("tab");

        if (tabIsDown && !tabWasDown) {
            isOpen = !isOpen; // toggle state
            updateImage();
        }

        // Track state for next frame
        tabWasDown = tabIsDown;
    }

    /**
     * Add an item to the inventory
     */
    public boolean addItem(InventoryItem item) {
        if (items.size() < maxSlots) {
            items.add(item);
            updateImage();
            return true;
        }
        return false; // Inventory full
    }

    /**
     * Remove an item from inventory
     */
    public boolean removeItem(InventoryItem item) {
        boolean removed = items.remove(item);
        if (removed) {
            updateImage();
        }
        return removed;
    }

    /**
     * Get item at specific slot
     */
    public InventoryItem getItem(int slot) {
        if (slot >= 0 && slot < items.size()) {
            return items.get(slot);
        }
        return null;
    }

    /**
     * Check if inventory contains an item type
     */
    public boolean hasItem(String itemName) {
        for (InventoryItem item : items) {
            if (item.getName().equals(itemName)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Redraw the inventory display
     */
    private void updateImage() {
        if (!isOpen) {
            // Show minimized icon
            this.setLocation(screenX, screenY);
            setImage(closedInv);
            return;
        }else{
            this.setLocation(screenX + 350, screenY - 250);
            setImage(openInv);
            return;
        }
        // TO DO: MAKE 2D ARRAY GRID FOR THE INVENTORY, MAKE THE ITEMS POP INTO THEM, IMPLEMENT DRAGGING ITEMS- ASK JULIAN FOR CODE
    }

    public int getItemCount() {
        return items.size();
    }

    public boolean isFull() {
        return items.size() >= maxSlots;
    }

    public void clear() {
        items.clear();
        updateImage();
    }
}

/**
 * Represents an item in the inventory
 */
class InventoryItem {
    private String name;
    private GreenfootImage icon;
    private int count;

    public InventoryItem(String name, GreenfootImage icon) {
        this(name, icon, 1);
    }

    public InventoryItem(String name, GreenfootImage icon, int count) {
        this.name = name;
        this.icon = icon;
        this.count = count;
    }

    public String getName() {
        return name;
    }

    public GreenfootImage getIcon() {
        return icon;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public void incrementCount() {
        count++;
    }

    public void decrementCount() {
        if (count > 0) count--;
    }
}