import greenfoot.*;
import java.util.ArrayList;

/**
 * A display that shows the player inventory, including weapons and items
 * 
 * Images generated by Leonardo.ai
 * 
 * @author Robin, Paul & Claude
 */
public class InventoryDisplay extends Display {
    // Image variables
    private GreenfootImage openInv = new GreenfootImage("openInv.png");
    private GreenfootImage closedInv = new GreenfootImage("closedInv.png");
    private boolean isOpen = false;
    private boolean tabWasDown = false;

    // Inventory utility
    private ArrayList<InventoryItem> items;
    private int[][] slotLocations; // set this
    private int maxSlots = 15;

    /**
     * Create inventory display at a fixed screen position
     * 
     * @param screenX X position on screen (not world position)
     * @param screenY Y position on screen (not world position)
     */
    public InventoryDisplay(int screenX, int screenY, Camera camera) {
        super(screenX, screenY, camera);
        this.items = new ArrayList<InventoryItem>();
        
        closedInv = scaleImage("closedInv.png", 100, 100, 225);
        openInv = scaleImage("openInv.png", 600, 600, 242);
        
        setImage(closedInv);
    }
    
    @Override
    protected void updateDisplay(){
        if(!isOpen){
            setLocation(screenX, screenY);
            setImage(closedInv);
        }else {
            setLocation(screenX + 350, screenY - 250);
            setImage(openInv);
        }
    }
    
    @Override
    public void act(){
        checkMouseClick();
        checkTabPress();
        updateDisplay();
    }

    private void checkMouseClick(){
        boolean mouseClickedInv = Greenfoot.mousePressed(this);
        boolean mouseIsDown = Greenfoot.mousePressed(null);
        
        if(!isOpen){
            // Click the icon to switch 
            if(mouseClickedInv){
                isOpen = true; // Toggle on new key press
            }
        }else {
            // Click outside of inventory to switch
            if(!mouseClickedInv && mouseIsDown){
                isOpen = false;
            }
        }
    }

    private void checkTabPress(){
        boolean tabIsDown = Greenfoot.isKeyDown("tab");

        if (tabIsDown && !tabWasDown) {
            isOpen = !isOpen; // toggle state
        }

        // Track state for next frame
        tabWasDown = tabIsDown;
    }

    // Inventory management methods
    /**
     * Add an item to the inventory
     */
    public boolean addItem(InventoryItem item) {
        if (items.size() < maxSlots) {
            items.add(item);
            return true;
        }
        return false; // Inventory full
    }

    /**
     * Remove an item from inventory
     */
    public boolean removeItem(InventoryItem item) {
        return items.remove(item);
    }

    /**
     * Get item at specific slot
     */
    public InventoryItem getItem(int slot) {
        if (slot >= 0 && slot < items.size()) {
            return items.get(slot);
        }
        return null;
    }

    /**
     * Check if inventory contains an item type
     */
    public boolean hasItem(String itemName) {
        for (InventoryItem item : items) {
            if (item.getName().equals(itemName)) {
                return true;
            }
        }
        return false;
    }
    
    public int getItemCount() {
        return items.size();
    }

    public boolean isFull() {
        return items.size() >= maxSlots;
    }

    public void clear() {
        items.clear();
    }
}

/**
 * Represents an item in the inventory
 */
class InventoryItem {
    private String name;
    private GreenfootImage icon;
    private int count;

    public InventoryItem(String name, GreenfootImage icon) {
        this(name, icon, 1);
    }

    public InventoryItem(String name, GreenfootImage icon, int count) {
        this.name = name;
        this.icon = icon;
        this.count = count;
    }

    public String getName() {
        return name;
    }

    public GreenfootImage getIcon() {
        return icon;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public void incrementCount() {
        count++;
    }

    public void decrementCount() {
        if (count > 0) count--;
    }
}