import greenfoot.*;
import java.util.ArrayList;
import java.util.List;


/**
 * A display that shows the player inventory, including weapons and items
 * 
 * Images generated by Leonardo.ai
 * 
 * @author Robin, Paul & Claude
 */
public class InventoryDisplay extends Display {
    // Image variables
    private GreenfootImage openInv = new GreenfootImage("openInv.png");
    private GreenfootImage closedInv = new GreenfootImage("closedInv.png");
    private GreenfootImage pt1 = new GreenfootImage("pt1.png");
    private GreenfootImage pt2 = new GreenfootImage("pt2.png");
    private GreenfootImage pt3 = new GreenfootImage("pt3.png");
    private GreenfootImage pt4 = new GreenfootImage("pt4.png");
    private boolean isOpen = false;
    private boolean tabWasDown = false;
    
    private Player player;

    // Inventory utility
    private ArrayList<InventoryItem> items;
    private int[][] slotLocations; 
    private final int maxSlots = 15;
    private final int COLS = 3;
    private final int ROWS = 5;

    /**
     * Create inventory display at a fixed screen position
     * 
     * @param screenX X position on screen (not world position)
     * @param screenY Y position on screen (not world position)
     */
    public InventoryDisplay(int screenX, int screenY, Camera camera, Player player) {
        super(screenX, screenY, camera);
        this.items = new ArrayList<InventoryItem>();
        this.player = player;
        
        closedInv = scaleImage("closedInv.png", 100, 100, 225);
        openInv = scaleImage("openInv.png", 600, 600, 242);
        
        // Initialize 2D coordinate map 
        createSlotMap();
        
        //Scale Images
        scaleImages();
        
        setImage(closedInv);
    }
    
    private void createSlotMap(){
        slotLocations = new int[15][2]; // Fixed: 15 slots, 2 coordinates each

        // Adjust these values to match where your grid starts in openInv.png
        int startX = 325; // X position of first slot
        int startY = 120;  // Y position of first slot
        int slotSpacing = 90; // Space between slot centers
        int slotsPerRow = 3;

        for (int i = 0; i < maxSlots; i++) {
            int row = i / slotsPerRow;
            int col = i % slotsPerRow;
            
            slotLocations[i][0] = startX + (col * slotSpacing);
            slotLocations[i][1] = startY + (row * slotSpacing);
        }
    }
    
    @Override
    protected void updateDisplay(){
        addToItems(player);
        if(!isOpen){
            setLocation(screenX, screenY);
            setImage(closedInv);
        }else {
            setLocation(screenX + 350, screenY - 250);
            
            // Create image with items
            GreenfootImage canvas = new GreenfootImage(openInv);
            drawItems(canvas);
            setImage(canvas);
        }
    }
    private void scaleImages(){
        pt1.scale(60,60);
        pt2.scale(60,60);
        pt3.scale(60,60);
        pt4.scale(60,60);
    }
    // Draws items on the inventory
    private void drawItems(GreenfootImage img){
         int index = 0;
         int minus = 0;
        for (int i = 0; i < items.size(); i++) {
            InventoryItem item = items.get(i);
            minus = 0;
            if (item.getCount() <= 0){
                minus = 1;
                continue;
            }
    
            GreenfootImage icon = item.getIcon();
            int x = slotLocations[index][0];
            int y = slotLocations[index][1];
    
            // Center the icon in the slot
            int iconX = x - (icon.getWidth() / 2);
            int iconY = y - (icon.getHeight() / 2);
    
            // Draw potion icon
            img.drawImage(icon, iconX, iconY);
    
            // Draw quantity text
            img.setFont(new Font("Arial", true, false, 24)); // Set font size
            img.setColor(Color.WHITE);
            img.drawString(
                String.valueOf(item.getCount()),
                x + 15,  // Adjust for text position
                y + 35
            );
            index = index + 1 - minus;
        }
    }
    
    @Override
    public void act(){
        checkMouseClick();
        checkTabPress();
        updateDisplay();
    }

    private void checkMouseClick(){
        boolean mouseClickedInv = Greenfoot.mousePressed(this);
        boolean mouseIsDown = Greenfoot.mousePressed(null);
        
        if(!isOpen){
            // Click the icon to switch 
            if(mouseClickedInv){
                isOpen = true; // Toggle on new key press
            }
        }else {
            // Click outside of inventory to switch
            if(!mouseClickedInv && mouseIsDown){
                isOpen = false;
            }
        }
    }

    private void checkTabPress(){
        boolean tabIsDown = Greenfoot.isKeyDown("tab");

        if (tabIsDown && !tabWasDown) {
            isOpen = !isOpen; // toggle state
        }

        // Track state for next frame
        tabWasDown = tabIsDown;
    }

    // Inventory management methods
    /**
     * Add an item to the inventory
     */
    public boolean addItem(InventoryItem item) {
        // Fixed: Removed items.clear() that was here
        if (items.size() < maxSlots) {
            items.add(item);
            return true;
        }
        return false; // Inventory full
    }
    
    public void addToItems(Player player){
        items.clear(); // Fixed: Clear before adding to prevent duplicates
        
        InventoryItem pot1 = new InventoryItem("potionOne", pt1, player.getItemCount(0));
        InventoryItem pot2 = new InventoryItem("potionTwo", pt2, player.getItemCount(1));
        InventoryItem pot3 = new InventoryItem("potionThree", pt3, player.getItemCount(2));
        InventoryItem pot4 = new InventoryItem("potionFour", pt4, player.getItemCount(3));
        
        items.addAll(List.of(pot1, pot2, pot3, pot4));
    }
    
    /**
     * Remove an item from inventory
     */
    public boolean removeItem(InventoryItem item) {
        return items.remove(item);
    }

    /**
     * Get item at specific slot
     */
    public InventoryItem getItem(int slot) {
        if (slot >= 0 && slot < items.size()) {
            return items.get(slot);
        }
        return null;
    }

    /**
     * Check if inventory contains an item type
     */
    public boolean hasItem(String itemName) {
        for (InventoryItem item : items) {
            if (item.getName().equals(itemName)) {
                return true;
            }
        }
        return false;
    }
    
    public int getItemCount() {
        return items.size();
    }

    public boolean isFull() {
        return items.size() >= maxSlots;
    }

    public void clear() {
        items.clear();
    }
}

/**
 * Represents an item in the inventory
 */
class InventoryItem {
    private String name;
    private GreenfootImage icon;
    private int count;

    public InventoryItem(String name, GreenfootImage icon) {
        this(name, icon, 1);
    }

    public InventoryItem(String name, GreenfootImage icon, int count) {
        this.name = name;
        this.icon = icon;
        this.count = count;
    }

    public String getName() {
        return name;
    }

    public GreenfootImage getIcon() {
        return icon;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public void incrementCount() {
        count++;
    }

    public void decrementCount() {
        if (count > 0) count--;
    }
}