import greenfoot.*;
import java.util.*;

/**
 * @author Julian
 * @version 2026
 * 
 * image generated by Google AI studio
 */
public abstract class NPC extends Actor
{    
    private int range = 100; // range at which NPCs will begin interacting with player
    private boolean promptVisible = false; //boolean that checks if the "Press 'E' to interact" is visible
    protected int fontSize = 12; // fontsize
    
    protected GreenfootImage image;
    public boolean isShopOpen = false; // boolean value that checks if the shop menu is open (for npcs that have shops)
    
    protected int offsetX = 0;
    protected int offsetY = -65;
    
    public void act()
    {
        interactWithPlayer();
    }

    /**
     * Method to show prompt and handle dialogue.
     * @author Julian
     */
    private void interactWithPlayer()
    {
        ArrayList<Player> playerInRange = (ArrayList<Player>)getObjectsInRange(range, Player.class);
        boolean playerNear = !playerInRange.isEmpty();

        if(playerNear)
        {
            if(!promptVisible && !isShopOpen)
            {
                textWriter("Press 'E' to interact", false);
                promptVisible = true;
            }
            if (("e").equals(Greenfoot.getKey())) {
                removeText();
                dialogue();
            }
        }
        else {
            if (promptVisible) {
                removeText();
                promptVisible = false;
                cleanUp();
            }
        }
    }

    //What the individual npcs do
    public abstract void dialogue();
    
    public void textWriter(String dialogue, boolean split)
    {
        TextManager.textBoxWriter(getWorld(), getX(), getY(), offsetX, offsetY, dialogue, fontSize, split);
    }
    
    public void removeText()
    {
        TextManager.removeText(getWorld());
    }
    
    /**
     * overrided method, cleans up whatever npcs need to cleanup
     */
    protected void cleanUp()
    {
        
    }
}