import greenfoot.*;
import java.util.*;

/**
 * @author Julian
 * @version 2026
 * 
 * image generated by Google AI studio
 */
public abstract class NPC extends Actor
{    
    private int range = 100; 
    private boolean promptVisible = false; 
    public int fontSize = 12;
    
    private TextBox textOne;
    private TextBox textTwo;
    private TextBox text;

    public void act()
    {
        interactWithPlayer();
    }

    /**
     * Method to show prompt and handle dialogue.
     * @author Julian
     */
    private void interactWithPlayer()
    {
        ArrayList<Player> playerInRange = (ArrayList<Player>)getObjectsInRange(range, Player.class);
        boolean playerNear = !playerInRange.isEmpty();

        if(playerNear)
        {
            if(!promptVisible)
            {
                textBoxWriter("Press 'E' to interact", false);
                promptVisible = true;
            }
            if (("e").equals(Greenfoot.getKey())) {
                removeText();
                dialogue();
            }
        }
        else {
            if (promptVisible) {
                removeText();
                promptVisible = false;
            }
        }
    }

    //What the individual npcs do
    public abstract void dialogue();

    /**
     * Method that handles making text objects
     * If the text is too long It splits it into two lines
     * @author Julian
     */
    public void textBoxWriter(String dialogue, boolean split)
    {
        removeText();
        if (split)
        {
            int index = 0;
            String lineOne = "";
            String lineTwo = "";
            for (int i = 0; i < dialogue.length()/2; i++)
            {
                index ++; 
                if(dialogue.charAt(i) =='|')
                {
                    lineOne = dialogue.substring(0,index - 1);
                    lineTwo = dialogue.substring(index);
                    break;
                }
            }

            textOne = new TextBox(lineOne, fontSize);
            textTwo = new TextBox(lineTwo, fontSize);

            getWorld().addObject(textOne, getX(), getY() - 80);
            getWorld().addObject(textTwo, getX(), getY() - 65);
        }

        else
        { 
            text = new TextBox(dialogue, fontSize);
            getWorld().addObject(text, getX(), getY() - 65);
        }
    }
    
    /**
     * Removes all text
     * @author Julian
     */
    public void removeText()
    {
        if (text != null && text.getWorld() != null)
        {
            getWorld().removeObject(text);
        }
        if (textOne != null && textOne.getWorld() != null)
        {
            getWorld().removeObject(textOne);
        }
        if (textTwo != null && textTwo.getWorld() != null)
        {
            getWorld().removeObject(textTwo);
        }
    }
}