import greenfoot.*;  
/**
 * The potion merchant in the game
 * 
 * @author Julian
 * @version 2026
 * 
 * Image generated by Google AI studio
 */

public class PotionMerchant extends NPC
{   
    private boolean textVisible = false;
    PotionShop shop;

    public PotionMerchant()
    {
        image = new GreenfootImage("potionMerchant.png");
        image.scale(image.getWidth()/3, image.getHeight()/3);
        setImage(image);
    }

    public void dialogue()
    {
        //if there is no text show question
        if (!textVisible) {
            textWriter("Would you like to | purchase potions? [E]", true);
            textVisible = true; 
        } 
        //if text is visible e was already pressed
        else if (!isShopOpen) {
            openShop();
        }
    }

    /**
     * Creates a PotionShop actor that contains icons, potions, and descritptions
     */
    private void openShop()
    {
        isShopOpen = true; 
        removeText();
        shop = new PotionShop();
        getWorld().addObject(shop, getWorld().getWidth()/2, getWorld().getHeight()/2);
    }
    
    @Override
    protected void cleanUp()
    {
        if (shop != null && shop.getWorld() != null) {
            shop.removeIcons();
            getWorld().removeObject(shop);
            shop = null;
        }
        isShopOpen = false; 
        textVisible = false; // reset to start conversation again
    }
}