import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class Merchant here.
 * 
 * @author Julian 
 * @version 2025
 * 
 * Image generated by Google AI Studio
 */
public class PotionMerchant extends NPC
{   
    private boolean textVisible = false;
    PotionShop shop;
    public PotionMerchant()
    {
        image = new GreenfootImage("potionMerchant.png");
        image.scale(image.getWidth()/3, image.getHeight()/3);
        setImage(image);
    }

    public void act()
    {
        super.act();
        if (getWorld().getObjects(TextBox.class).isEmpty()) {
            textVisible = false;
        }
    }

    public void dialogue()
    {
        //only writes text if its not already there
        if (!textVisible && !isShopOpen) {
            textWriter("Would you like to | purchase potions? [E]", true);
            textVisible = true; 
        }
        String key = Greenfoot.getKey();
        if (Greenfoot.isKeyDown("e") && !isShopOpen) {
            openShop();
        }
    }

    private void openShop()
    {
        isShopOpen = true; 
        removeText();
        
        shop = new PotionShop();
        getWorld().addObject(shop, getWorld().getWidth()/2, getWorld().getHeight()/2);
    }
    
    @Override
    protected void cleanUp()
    {
        if (shop != null && shop.getWorld() != null) {
            getWorld().removeObject(shop);
            shop = null;
        }
        isShopOpen = false; 
        textVisible = false;
    }
}
